[package]
name = "fri"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pasta_curves = "0.4.1"
keccak = "0.1.3"
ff = "0.12.0"
merlin = "3.0.0"
poseidon = { path = "./poseidon" }